//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommerceEntities : DbContext
    {
        public EcommerceEntities()
            : base("name=EcommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_CATEGORIA> TBL_CATEGORIA { get; set; }
        public virtual DbSet<TBL_CLIENTE> TBL_CLIENTE { get; set; }
        public virtual DbSet<TBL_DETALLE_IMPUESTOS> TBL_DETALLE_IMPUESTOS { get; set; }
        public virtual DbSet<TBL_DETALLE_PEDIDO> TBL_DETALLE_PEDIDO { get; set; }
        public virtual DbSet<TBL_DIRECCION> TBL_DIRECCION { get; set; }
        public virtual DbSet<TBL_FORMA_PAGO> TBL_FORMA_PAGO { get; set; }
        public virtual DbSet<TBL_IMPUESTOS> TBL_IMPUESTOS { get; set; }
        public virtual DbSet<TBL_PAGOS> TBL_PAGOS { get; set; }
        public virtual DbSet<TBL_PEDIDO> TBL_PEDIDO { get; set; }
        public virtual DbSet<TBL_PRODUCTO> TBL_PRODUCTO { get; set; }
        public virtual DbSet<TBL_ROL> TBL_ROL { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
