//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_IMPUESTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_IMPUESTOS()
        {
            this.TBL_DETALLE_IMPUESTOS = new HashSet<TBL_DETALLE_IMPUESTOS>();
        }
    
        public int IMP_ID { get; set; }
        public string IMP_CODIGO_SRI { get; set; }
        public string IMP_DESCRIPCION { get; set; }
        public Nullable<decimal> IMP_PORCENTAJE { get; set; }
        public string IMP_ESTADO { get; set; }
        public Nullable<System.DateTime> IMP_FECHA_CREACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLE_IMPUESTOS> TBL_DETALLE_IMPUESTOS { get; set; }
    }
}
