//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public int USU_ID { get; set; }
        public Nullable<int> ROL_ID { get; set; }
        public string USU_CORREO { get; set; }
        public string USU_CONTRASENA { get; set; }
        public string USU_NOMBRES { get; set; }
        public string USU_APELLIDOS { get; set; }
        public string USU_ESTADO { get; set; }
        public Nullable<System.DateTime> USU_FECHA_CREACION { get; set; }
    
        public virtual TBL_ROL TBL_ROL { get; set; }
    }
}
